import type { Metadata } from 'next'
import { Toaster } from 'sonner'
// These styles apply to every route in the application
import './globals.css'
import BackgroundFX from '@/components/BackgroundFX'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <BackgroundFX />
        <div className="relative z-10">
          {children}
          <Toaster />
        </div>
      </body>
    </html>
  )
}